### ISSUE TITLE
SendStickersaslink cant destructure property 'StickerSendability'

### ISSUE THREAD

**Issue by Hackatoan** [Skamt/BDAddons#35]
Error when trying to use the sendstickersaslink plugin

`TypeError: Cannot destructure property 'StickerSendability' of 'StickerSendability' as it is undefined.
    at eval (betterdiscord://plugins/SendStickersAsLinks.plugin.js:329:29)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201`

**Comment by Skamt** [comment]
fixed
