### ISSUE TITLE
ERROR WITH PLUGIN 

### ISSUE THREAD

**Issue by AgarHeroYT9** [Skamt/BDAddons#36]
TypeError: Cannot destructure property 'StickerSendability' of 'StickerSendability' as it is undefined.
    at eval (betterdiscord://plugins/SendStickersAsLinks.plugin.js:329:29)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by Skamt** [comment]
#35
