### ISSUE TITLE
Bug: Simplified Profiles seem to break plugin

### ISSUE THREAD

**Issue by thelegendfox** [Skamt/BDAddons#38]
Hiya! Discord forced me to use the new "simplified profiles", and now I'm getting this error and it won't compile. Thank you!

```TypeError: Cannot read properties of undefined (reading 'ImageModal')
    at eval (betterdiscord://plugins/ViewProfilePicture.plugin.js:240:41)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)```

**Comment by Skamt** [comment]
a fix has been pushed, wait for approval.
