### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Darkn8tT** [Skamt/BDAddons#39]
TypeError: Cannot read properties of undefined (reading 'ImageModal')
    at eval (betterdiscord://plugins/ViewProfilePicture.plugin.js:240:41)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235

**Comment by Skamt** [comment]
Been fixed, wait for approval.
