### ISSUE TITLE
PLugin ERROR

### ISSUE THREAD

**Issue by AgarHeroYT** [Skamt/BDAddons#41]
TypeError: Cannot read properties of undefined (reading 'ZP')
    at eval (betterdiscord://plugins/ViewProfilePicture.plugin.js:333:16)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235

**Comment by Skamt** [comment]
fixed in the next update, await approval

**Comment by MagmaBro123** [comment]
> fixed in the next update, await approval

You have new issues.
