### ISSUE TITLE
ViewProfilePicture Plugin Could Not Be Compiled

### ISSUE THREAD

**Issue by Kitsu-76** [Skamt/BDAddons#46]
TypeError: zustand is not a function
    at eval (betterdiscord://plugins/ViewProfilePicture.plugin.js:72:2)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201

![image](https://github.com/user-attachments/assets/f2882948-8d7d-4de9-8730-0fc29f61b2dc)

**Comment by ressamark** [comment]
Download the new version (1.2.12) here in github, it fixes this
