### ISSUE TITLE
Sticker preview is still broken

### ISSUE THREAD

**Issue by EnoralTheOutCast** [Skamt/BDAddons#59]
The title explains it.. It's still broken after one of the recent BD updates or something.

**Comment by Skamt** [comment]
![image](https://github.com/user-attachments/assets/1ba84155-3e06-4aeb-bc06-3f15d9c09c73)

seems to work, are you on the latest version ?

**Comment by EnoralTheOutCast** [comment]
Yeah. Plugin version 1.2.3
BD version 1.11.0

**Comment by EnoralTheOutCast** [comment]
It doesn't load up with the 'could not be compiled error

SyntaxError: Unexpected token '', ""... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.ensurePluginData (betterdiscord/renderer.js:5:15980)
    at Object.getPluginData (betterdiscord/renderer.js:5:16081)
    at Dt.load (betterdiscord/renderer.js:5:418071)
    at eval (betterdiscord://plugins/StickerEmojiPreview.plugin.js:141:14)
    at eval (betterdiscord://plugins/StickerEmojiPreview.plugin.js:132:56)
    at i (https://discord.com/assets/web.32d39ccf088c3f500ddd.js:12:11611943)
    at a (https://discord.com/assets/web.32d39ccf088c3f500ddd.js:12:11611969)
    at c (https://discord.com/assets/web.32d39ccf088c3f500ddd.js:12:11611511)
    at d (https://discord.com/assets/web.32d39ccf088c3f500ddd.js:12:11611575)
    at eval (betterdiscord://plugins/StickerEmojiPreview.plugin.js:135:2)
    at N.requireAddon (betterdiscord/renderer.js:5:30017)
    at N.loadAddon (betterdiscord/renderer.js:5:7628)
    at N.loadAddon (betterdiscord/renderer.js:5:27685)
    at N.loadAllAddons (betterdiscord/renderer.js:5:10685)
    at N.initialize (betterdiscord/renderer.js:5:4500)
    at N.initialize (betterdiscord/renderer.js:5:26798)
    at Object.startup (betterdiscord/renderer.js:5:416934)

**Comment by Skamt** [comment]
Go to the plugins folder and delete the config file `StickerEmojiPreview.config.json`, make sure discord is closed before you do this

**Comment by EnoralTheOutCast** [comment]
Okay it fixed, thanks Skamt
