### ISSUE TITLE
[BUG] Causes discord to crash

### ISSUE THREAD

**Issue by aaronliu0130** [Skamt/BDAddons#8]
````
[2023-03-01 20:11:40.476][CONSOLE:ERROR] Cannot read property 'LEFT' of undefined
TypeError: Cannot read property 'LEFT' of undefined
    at previewComponent (betterdiscord://plugins/StickerEmojiPreview.plugin.js:57:33)
    at Sa (https://discord.com/assets/3ce5a3a3ee1992708511.js:1654:54)
    at yu (https://discord.com/assets/3ce5a3a3ee1992708511.js:1708:146)
    at Oc (https://discord.com/assets/3ce5a3a3ee1992708511.js:1701:89)
    at Ic (https://discord.com/assets/3ce5a3a3ee1992708511.js:1701:17)
    at hc (https://discord.com/assets/3ce5a3a3ee1992708511.js:1700:867)
    at ic (https://discord.com/assets/3ce5a3a3ee1992708511.js:1697:642)
    at uc (https://discord.com/assets/3ce5a3a3ee1992708511.js:1698:49)
    at Fo (https://discord.com/assets/3ce5a3a3ee1992708511.js:1637:577)
    at https://discord.com/assets/3ce5a3a3ee1992708511.js:1695:555
[2023-03-01 20:11:42.830][CONSOLE:DEBUG] [ChannelMessagePreviewStore] Persisting store
[2023-03-01 20:11:43.821][CONSOLE:WARN] Window state not initialized window-1
```

**Comment by Skamt** [comment]
Fix [3d36ffa](https://github.com/Skamt/BDAddons/commit/3d36ffac4c34fcf67c440d8a9b82c0af2f68b6d2) has been pushed, waiting approval
